services:
  - type: web
    name: convert-ai-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    numInstances: 1
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
